.equ LOCALID_KLAWF, 6

Route106_MapScripts::
	.byte 0

Route106_EventScript_TrainerTipsSign::
	msgbox Route106_Text_TrainerTips, MSGBOX_SIGN
	end

Route106_EventScript_Douglas::
	trainerbattle_single TRAINER_DOUGLAS, Route106_Text_DouglasIntro, Route106_Text_DouglasDefeated
	msgbox Route106_Text_DouglasPostBattle, MSGBOX_AUTOCLOSE
	end

Route106_EventScript_Kyla::
	trainerbattle_single TRAINER_KYLA, Route106_Text_KylaIntro, Route106_Text_KylaDefeated
	msgbox Route106_Text_KylaPostBattle, MSGBOX_AUTOCLOSE
	end

Route106_EventScript_Elliot::
	trainerbattle_single TRAINER_ELLIOT_1, Route106_Text_ElliotIntro, Route106_Text_ElliotDefeated, Route106_EventScript_ElliotRegisterMatchCallAfterBattle
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, Route106_EventScript_ElliotRematch
	msgbox Route106_Text_ElliotPostBattle, MSGBOX_DEFAULT
	release
	end

Route106_EventScript_ElliotRegisterMatchCallAfterBattle::
	special PlayerFaceTrainerAfterBattle
	waitmovement 0
	msgbox Route106_Text_ElliotRegister, MSGBOX_DEFAULT
	register_matchcall TRAINER_ELLIOT_1
	release
	end

Route106_EventScript_ElliotRematch::
	trainerbattle_rematch TRAINER_ELLIOT_1, Route106_Text_ElliotRematchIntro, Route106_Text_ElliotRematchDefeated
	msgbox Route106_Text_ElliotRematchPostBattle, MSGBOX_AUTOCLOSE
	end

Route106_EventScript_Ned::
	trainerbattle_single TRAINER_NED, Route106_Text_NedIntro, Route106_Text_NedDefeated
	msgbox Route106_Text_NedPostBattle, MSGBOX_AUTOCLOSE
	end

Route106_EventScript_KlawfTitan::
	goto_if_eq VAR_PATH, 2, Route106_EventScript_KlawfTitanReverse
	setvar VAR_TEMP_F, 15
	buffernumberstring STR_VAR_2, VAR_TEMP_F
	goto_if_lt VAR_LEVEL_CAP, VAR_TEMP_F, Common_EventScript_CheckIfLevelCapTooLow
	lock
	faceplayer
	msgbox gText_PlaceHolder, MSGBOX_DEFAULT
	titanbattle 1
	waitstate
	msgbox gText_PlaceHolder, MSGBOX_DEFAULT
	titanbattle 2
	waitstate
	fadescreen FADE_TO_BLACK
	removeobject LOCALID_KLAWF
	setflag FLAG_TITAN_KLAWF
	fadescreen FADE_FROM_BLACK
	call Common_EventScript_AddMoneyScrambledTitanFights
	setvar VAR_LEVEL_CAP 18
	call Common_EventScript_NewLevelCapTextAndTopupItemsAndFanfare
	release
	end

Route106_EventScript_KlawfTitanReverse::
	setvar VAR_TEMP_F, 58
	buffernumberstring STR_VAR_2, VAR_TEMP_F
	goto_if_lt VAR_LEVEL_CAP, VAR_TEMP_F, Common_EventScript_CheckIfLevelCapTooLow
	lock
	faceplayer
	msgbox gText_PlaceHolder, MSGBOX_DEFAULT
	titanbattle 26
	waitstate
	msgbox gText_PlaceHolder, MSGBOX_DEFAULT
	titanbattle 27
	waitstate
	fadescreen FADE_TO_BLACK
	removeobject LOCALID_KLAWF
	setflag FLAG_TITAN_KLAWF
	fadescreen FADE_FROM_BLACK
	call Common_EventScript_AddMoneyScrambledTitanFights
	setvar VAR_LEVEL_CAP 60
	call Common_EventScript_NewLevelCapTextAndTopupItemsAndFanfare
	release
	end

Route106_Text_TrainerTips:
	.string "TRAINER TIPS\p"
	.string "Advice on catching POKéMON with a ROD:\n"
	.string "Press the A Button if you get a bite.$"
