.set LOCALID_MART_EMPLOYEE, 2
.set LOCALID_FOOTPRINTS_MAN, 3
.set LOCALID_RIVAL, 4
.set LOCALID_CARMINE, 5
.set LOCALID_KIERAN, 6
.set LOCALID_CARMINE2, 7

OldaleTown_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, OldaleTown_OnTransition
	.byte 0

OldaleTown_OnTransition:
	call Common_EventScript_SetupRivalGfxId
	setflag FLAG_VISITED_OLDALE_TOWN
	call_if_unset FLAG_ADVENTURE_STARTED, OldaleTown_EventScript_BlockWestEntrance
	call_if_unset FLAG_RECEIVED_POTION_OLDALE, OldaleTown_EventScript_MoveMartEmployee
	call_if_set FLAG_ADVENTURE_STARTED, OldaleTown_EventScript_SetOldaleState
	call_if_ge VAR_LEVEL_CAP, 20, OldaleTown_EventScript_RemoveKieran1
	call_if_set FLAG_BADGE03_GET, OldaleTown_EventScript_SwapCarmine1ForCarmine2
	end

@ This script seems pointless because nothing uses VAR_OLDALE_TOWN_STATE
OldaleTown_EventScript_SetOldaleState::
	setvar VAR_OLDALE_TOWN_STATE, 1
	return

OldaleTown_EventScript_BlockWestEntrance::
	setobjectxyperm LOCALID_FOOTPRINTS_MAN, 1, 11
	setobjectmovementtype LOCALID_FOOTPRINTS_MAN, MOVEMENT_TYPE_FACE_LEFT
	return

OldaleTown_EventScript_MoveMartEmployee::
	setobjectxyperm LOCALID_MART_EMPLOYEE, 13, 14
	setobjectmovementtype LOCALID_MART_EMPLOYEE, MOVEMENT_TYPE_FACE_DOWN
	return

OldaleTown_EventScript_RemoveKieran1::
	setobjectxyperm LOCALID_KIERAN, 26, -1
	return

OldaleTown_EventScript_SwapCarmine1ForCarmine2::
	setobjectxyperm LOCALID_CARMINE, 25, -1
	setobjectxyperm LOCALID_CARMINE2, 10, 10
	setobjectmovementtype LOCALID_MART_EMPLOYEE, MOVEMENT_TYPE_LOOK_AROUND
	return

OldaleTown_EventScript_TownSign::
	msgbox OldaleTown_Text_TownSign, MSGBOX_SIGN
	end

OldaleTown_EventScript_Girl::
	msgbox OldaleTown_Text_SavingMyProgress, MSGBOX_NPC
	end

OldaleTown_EventScript_MartEmployee::
	lock
	faceplayer
	goto_if_set FLAG_RECEIVED_POTION_OLDALE, OldaleTown_EventScript_ExplainPotion
	goto_if_set FLAG_TEMP_1, OldaleTown_EventScript_ExplainPotion
	setflag FLAG_TEMP_1
	playbgm MUS_FOLLOW_ME, FALSE
	msgbox OldaleTown_Text_IWorkAtPokemonMart, MSGBOX_DEFAULT
	closemessage
	switch VAR_FACING
	case DIR_SOUTH, OldaleTown_EventScript_GoToMartSouth
	case DIR_NORTH, OldaleTown_EventScript_GoToMartNorth
	case DIR_EAST, OldaleTown_EventScript_GoToMartEast
	end

OldaleTown_EventScript_GoToMartSouth::
	applymovement LOCALID_MART_EMPLOYEE, OldaleTown_Movement_EmployeeSouth
	applymovement OBJ_EVENT_ID_PLAYER, OldaleTown_Movement_PlayerSouth
	waitmovement 0
	goto OldaleTown_EventScript_ExplainPokemonMart
	end

OldaleTown_EventScript_GoToMartNorth::
	applymovement LOCALID_MART_EMPLOYEE, OldaleTown_Movement_EmployeeNorth
	applymovement OBJ_EVENT_ID_PLAYER, OldaleTown_Movement_PlayerNorth
	waitmovement 0
	goto OldaleTown_EventScript_ExplainPokemonMart
	end

OldaleTown_EventScript_GoToMartEast::
	applymovement OBJ_EVENT_ID_PLAYER, OldaleTown_Movement_PlayerEast
	applymovement LOCALID_MART_EMPLOYEE, OldaleTown_Movement_EmployeeEast
	waitmovement 0
	goto OldaleTown_EventScript_ExplainPokemonMart
	end

OldaleTown_EventScript_ExplainPokemonMart::
	msgbox OldaleTown_Text_ThisIsAPokemonMart, MSGBOX_DEFAULT
	giveitem ITEM_POTION
	goto_if_eq VAR_RESULT, FALSE, OldaleTown_EventScript_BagIsFull
	msgbox OldaleTown_Text_PotionExplanation, MSGBOX_DEFAULT
	setflag FLAG_RECEIVED_POTION_OLDALE
	fadedefaultbgm
	release
	end

OldaleTown_EventScript_ExplainPotion::
	msgbox OldaleTown_Text_PotionExplanation, MSGBOX_DEFAULT
	release
	end

OldaleTown_EventScript_BagIsFull::
	msgbox gText_TooBadBagIsFull, MSGBOX_DEFAULT
	fadedefaultbgm
	release
	end

OldaleTown_Movement_EmployeeEast:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_in_place_faster_down
	step_end

OldaleTown_Movement_EmployeeSouth:
	walk_left
	walk_up
	walk_up
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_in_place_faster_down
	step_end

OldaleTown_Movement_EmployeeNorth:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_in_place_faster_down
	step_end

OldaleTown_Movement_Unknown1:
	walk_up
	walk_up
	walk_right
	walk_right
	walk_right
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	delay_8
	walk_in_place_faster_down
	step_end

OldaleTown_Movement_PlayerEast:
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

OldaleTown_Movement_PlayerSouth:
	delay_16
	delay_16
	delay_16
	delay_16
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

OldaleTown_Movement_PlayerNorth:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

OldaleTown_Movement_Unknown2:
	walk_left
	walk_up
	walk_up
	walk_right
	walk_right
	walk_right
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

OldaleTown_EventScript_FootprintsMan::
	lock
	faceplayer
	goto_if_set FLAG_ADVENTURE_STARTED, OldaleTown_EventScript_NotBlockingPath
	msgbox OldaleTown_Text_DiscoveredFootprints, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_FOOTPRINTS_MAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

OldaleTown_EventScript_BlockedPath::
	lockall
	applymovement OBJ_EVENT_ID_PLAYER, OldaleTown_Movement_PlayerStepBack
	applymovement LOCALID_FOOTPRINTS_MAN, OldaleTown_Movement_BackUp
	waitmovement 0
	msgbox OldaleTown_Text_WaitDontComeInHere, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_FOOTPRINTS_MAN, OldaleTown_Movement_ReturnToOriginalPosition
	waitmovement 0
	releaseall
	end

OldaleTown_EventScript_NotBlockingPath::
	msgbox OldaleTown_Text_FinishedSketchingFootprints, MSGBOX_DEFAULT
	release
	end

OldaleTown_EventScript_Rival::
	lockall
	applymovement LOCALID_RIVAL, Common_Movement_FacePlayer
	waitmovement 0
	setvar VAR_0x8009, 0
	goto OldaleTown_EventScript_ShowRivalMessage
	end

OldaleTown_EventScript_RivalTrigger1::
	lockall
	applymovement LOCALID_RIVAL, OldaleTown_Movement_RivalApproachPlayer1
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	setvar VAR_0x8009, 1
	goto OldaleTown_EventScript_ShowRivalMessage
	end

OldaleTown_EventScript_RivalTrigger2::
	lockall
	applymovement LOCALID_RIVAL, OldaleTown_Movement_RivalApproachPlayer2
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	setvar VAR_0x8009, 1
	goto OldaleTown_EventScript_ShowRivalMessage
	end

OldaleTown_EventScript_RivalTrigger3::
	lockall
	applymovement LOCALID_RIVAL, OldaleTown_Movement_RivalApproachPlayer3
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	setvar VAR_0x8009, 1
	goto OldaleTown_EventScript_ShowRivalMessage
	end

OldaleTown_EventScript_ShowRivalMessage::
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, OldaleTown_EventScript_ShowMayMessage
	goto_if_eq VAR_RESULT, FEMALE, OldaleTown_EventScript_ShowBrendanMessage
	end

OldaleTown_EventScript_ShowMayMessage::
	msgbox OldaleTown_Text_MayLetsGoBack, MSGBOX_DEFAULT
	goto OldaleTown_EventScript_RivalFinish
	end

OldaleTown_EventScript_ShowBrendanMessage::
	msgbox OldaleTown_Text_BrendanLetsGoBack, MSGBOX_DEFAULT
	goto OldaleTown_EventScript_RivalFinish
	end

OldaleTown_EventScript_RivalFinish::
	closemessage
	call_if_eq VAR_0x8009, 0, OldaleTown_EventScript_DoExitMovement1
	call_if_eq VAR_0x8009, 1, OldaleTown_EventScript_DoExitMovement2
	applymovement LOCALID_RIVAL, OldaleTown_Movement_RivalExit
	waitmovement 0
	removeobject LOCALID_RIVAL
	setvar VAR_OLDALE_RIVAL_STATE, 2
	setflag FLAG_HIDE_OLDALE_TOWN_RIVAL
	releaseall
	end

OldaleTown_EventScript_DoExitMovement1::
	goto_if_ne VAR_FACING, DIR_SOUTH, OldaleTown_EventScript_DoExitMovement2
	applymovement LOCALID_RIVAL, OldaleTown_Movement_RivalExit
	waitmovement 0
	return

OldaleTown_EventScript_DoExitMovement2::
	applymovement OBJ_EVENT_ID_PLAYER, OldaleTown_Movement_WatchRivalExit
	applymovement LOCALID_RIVAL, OldaleTown_Movement_RivalExit
	waitmovement 0
	return

OldaleTown_Movement_RivalApproachPlayer1:
	walk_left
	walk_left
	step_end

OldaleTown_Movement_RivalApproachPlayer2:
	walk_left
	step_end

OldaleTown_Movement_RivalApproachPlayer3:
	face_left
	step_end

OldaleTown_Movement_RivalExit:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	step_end

OldaleTown_Movement_WatchRivalExit:
	delay_8
	delay_4
	walk_in_place_faster_down
	step_end

OldaleTown_Movement_PlayerStepBack:
	delay_8
	walk_right
	step_end

OldaleTown_Movement_BackUp:
	walk_fast_up
	walk_in_place_faster_left
	lock_facing_direction
	walk_right
	unlock_facing_direction
	step_end

OldaleTown_Movement_ReturnToOriginalPosition:
	walk_down
	walk_left
	step_end

OldaleTown_EventScript_Carmine1::
	@ Ask if skipping Teal Mask ONLY IF NOT SELECTED
	goto_if_eq VAR_LEVEL_CAP, 11, OldaleTown_EventScript_Carmine1_SkipKitakamiQuestion
	goto_if_set FLAG_SKIPPING_TEAL_MASK, OldaleTown_EventScript_Carmine1_Skipped
	goto OldaleTown_EventScript_Carmine1Battle

OldaleTown_EventScript_Carmine1Battle::
	trainerbattle_single TRAINER_SISTER_01_01, OldaleTown_Text_Carmine1Intro, OldaleTown_Text_Carmine1Defeat, OldaleTown_EventScript_Carmine1_Defeated
	msgbox OldaleTown_Text_Carmine1PostBattle, MSGBOX_DEFAULT
	release
	end

OldaleTown_EventScript_Carmine1_SkipKitakamiQuestion::
	lock
	faceplayer
	msgbox OldaleTown_Text_CarmineAskSkipKitakami, MSGBOX_DEFAULT
	multichoice 20, 8, MULTI_YESNO, TRUE
	goto_if_eq VAR_RESULT, 0, OldaleTown_EventScript_Carmine1Battle
	goto_if_eq VAR_RESULT, 1, OldaleTown_EventScript_Carmine1_SkipKitakamiAreYouSure

OldaleTown_EventScript_Carmine1_Skipped::
	lock
	faceplayer
	msgbox OldaleTown_Text_Carmine1PostBattle, MSGBOX_DEFAULT
	release
	end

OldaleTown_EventScript_Carmine1_SkipKitakamiAreYouSure::
	lock
	faceplayer
	msgbox OldaleTown_Text_CarmineAskAreYouSure, MSGBOX_DEFAULT
	multichoice 20, 8, MULTI_YESNO, TRUE
	goto_if_eq VAR_RESULT, 0, OldaleTown_EventScript_Carmine1_SkipKitakamiAww
	goto_if_eq VAR_RESULT, 1, OldaleTown_EventScript_Carmine1_SkipKitakamiQuestion
	return

OldaleTown_EventScript_Carmine1_SkipKitakamiAww::
	msgbox OldaleTown_Text_CarmineSkipKitakamiAww, MSGBOX_DEFAULT
	setflag FLAG_SKIPPING_TEAL_MASK
	call OldaleTown_EventScript_Kieran1_Defeated
	release
	end

OldaleTown_EventScript_Carmine1_Defeated::
	setvar VAR_LEVEL_CAP 12
	call Common_EventScript_NewLevelCapTextAndTopupItemsAndFanfare
	return

OldaleTown_EventScript_Carmine2::
	goto_if_set FLAG_SKIPPING_TEAL_MASK, OldaleTown_EventScript_Carmine2_Skipped
	setvar VAR_TEMP_F, 32
	buffernumberstring STR_VAR_2, VAR_TEMP_F
	goto_if_lt VAR_LEVEL_CAP, VAR_TEMP_F, Common_EventScript_CheckIfLevelCapTooLow
	trainerbattle_single TRAINER_SISTER_01_02, OldaleTown_Text_Carmine2Intro, OldaleTown_Text_Carmine2Defeat, OldaleTown_EventScript_Carmine2_Defeated
	msgbox OldaleTown_Text_Carmine2PostBattle, MSGBOX_DEFAULT
	release
	end

OldaleTown_EventScript_Carmine2_Skipped::
	lock
	faceplayer
	msgbox OldaleTown_Text_Carmine2PostBattle, MSGBOX_DEFAULT
	release
	end

OldaleTown_EventScript_Carmine2_Defeated::
	setvar VAR_LEVEL_CAP 33
	call Common_EventScript_NewLevelCapTextAndTopupItemsAndFanfare
	return

OldaleTown_EventScript_Kieran1::
	goto_if_set FLAG_SKIPPING_TEAL_MASK, OldaleTown_EventScript_Kieran1_Skipped
	setvar VAR_TEMP_F, 12
	buffernumberstring STR_VAR_2, VAR_TEMP_F
	goto_if_lt VAR_LEVEL_CAP, VAR_TEMP_F, Common_EventScript_CheckIfLevelCapTooLow
	trainerbattle_single TRAINER_BROTHER_01_01, OldaleTown_Text_Kieran1Intro, OldaleTown_Text_Kieran1Defeat, OldaleTown_EventScript_Kieran1_Defeated
	msgbox OldaleTown_Text_Kieran1PostBattle, MSGBOX_AUTOCLOSE
	release
	end

OldaleTown_EventScript_Kieran1_Skipped::
	lock
	faceplayer
	msgbox OldaleTown_Text_Kieran1PostBattle, MSGBOX_AUTOCLOSE
	release
	end

OldaleTown_EventScript_Kieran1_Defeated::
	setvar VAR_LEVEL_CAP 13
	call Common_EventScript_NewLevelCapTextAndTopupItemsAndFanfare
	giveitem ITEM_FLYING_TAXI_TICKET
	return

OldaleTown_Text_CarmineAskSkipKitakami:
	.string "Surely you are interested in\n"
	.string "the lore of the {COLOR RED}Teal Mask{COLOR DARK_GRAY}, right?$"

OldaleTown_Text_CarmineAskAreYouSure:
	.string "Woah! You really want to {COLOR RED}SKIP{COLOR DARK_GRAY} Kitakami?\n"
	.string "You {COLOR RED}CANNOT{COLOR DARK_GRAY} change this later!$"

OldaleTown_Text_CarmineSkipKitakamiAww:
	.string "Aww, really?\n"
	.string "Alright, fine then…$"

OldaleTown_Text_Carmine1Intro:
	.string "We must have been fated to meet.\n"
	.string "May I ask you for a battle?$"

OldaleTown_Text_Carmine1Defeat:
	.string "Oh, my!$"

OldaleTown_Text_Carmine1PostBattle:
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"

OldaleTown_Text_Carmine2Intro:
	.string "Since I bathed in the hot springs,\n"
	.string "I've been feeling great!\l"
	.string "I'm sure I'm going to win!$"

OldaleTown_Text_Carmine2Defeat:
	.string "Yowch!\n"
	.string "I'm getting a chill out of the water.$"

OldaleTown_Text_Carmine2PostBattle:
	.string "I'll have to take another dip in the\n"
	.string "hot springs. Want to join me?\p"
	.string "Just joking!$"

OldaleTown_Text_SavingMyProgress:
	.string "I want to take a rest, so I'm saving my\n"
	.string "progress.$"

OldaleTown_Text_IWorkAtPokemonMart:
	.string "Hi!\n"
	.string "I work at a POKéMON MART.\p"
	.string "Can I get you to come with me?$"

OldaleTown_Text_ThisIsAPokemonMart:
	.string "This is a POKéMON MART.\n"
	.string "Just look for our blue roof.\p"
	.string "We sell a variety of goods including\n"
	.string "POKé BALLS for catching POKéMON.\p"
	.string "Here, I'd like you to have this as\n"
	.string "a promotional item.$"

OldaleTown_Text_PotionExplanation:
	.string "A POTION can be used anytime, so it's\n"
	.string "even more useful than a POKéMON CENTER\l"
	.string "in certain situations.$"

OldaleTown_Text_WaitDontComeInHere:
	.string "Aaaaah! Wait!\n"
	.string "Please don't come in here.\p"
	.string "I just discovered the footprints of\n"
	.string "a rare POKéMON!\p"
	.string "Wait until I finish sketching\n"
	.string "them, okay?$"

OldaleTown_Text_DiscoveredFootprints:
	.string "I just discovered the footprints of\n"
	.string "a rare POKéMON!\p"
	.string "Wait until I finish sketching\n"
	.string "them, okay?$"

OldaleTown_Text_FinishedSketchingFootprints:
	.string "I finished sketching the footprints of\n"
	.string "a rare POKéMON.\p"
	.string "But it turns out they were only my\n"
	.string "own footprints…$"

OldaleTown_Text_MayLetsGoBack:
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "Over here!\l"
	.string "Let's hurry home!$"

OldaleTown_Text_BrendanLetsGoBack:
	.string "BRENDAN: I'm heading back to my dad's\n"
	.string "LAB now.\l"
	.string "{PLAYER}, you should hustle back, too.$"

OldaleTown_Text_TownSign:
	.string "OLDALE TOWN\n"
	.string "“Where things start off scarce.”$"

OldaleTown_Text_Kieran1Intro:
	.string "Why keep it a secret?\n"
	.string "I'm the WATER POKéMON expert!\p"
	.string "Huh?\n"
	.string "You don't know me?$"

OldaleTown_Text_Kieran1Defeat:
	.string "I thought I wasn't too bad, if I may\n"
	.string "say so, but I guess not… Bleah…$"

OldaleTown_Text_Kieran1PostBattle:
	.string "I got too into fishing.\n"
	.string "I forgot I had to raise my POKéMON…$"
